name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "19 6 * * MON-FRI" # Every weekday
jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@7fb82c71087c04bf9416cf8e91902bde045c878c # v2.22.2
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
