name: Security veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "34 6 * * 1" # Every Monday
jobs:
  security-veracode-policy-check:
    name: Project security veracode policy scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@7fb82c71087c04bf9416cf8e91902bde045c878c # v2.22.2
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
