name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "19 6 * * MON-FRI" # Every weekday
jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@7fb82c71087c04bf9416cf8e91902bde045c878c # v2.22.2
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
